### ISSUE TITLE
project todo list

### ISSUE THREAD

**Issue by lantanRain** [lantanRain/in_memory_cache#1]
- [x] rest api
- [x] project package struct (고민 DDD? multi-module?)
- [ ] in-memory cache
- [x] local db & CRUD action
- [ ]
