### ISSUE TITLE
todo api

### ISSUE THREAD

**Issue by lantanRain** [lantanRain/in_memory_cache#2]
### 요구사항
* case4 . response 또는 data miss 처리 (business logic에서는 1차적으로 exception handler 처리
* case5. cache service와 별도의 transaction처리가 필요함 (api분리)
               service api에서 CRUD, cache api에서 CRUD 기능 각각 구현 필요

### api construct todo 
- [x] 기본구조 잡기
- [x] RestController & Response
- [ ]  servlet 필요할까?
- [x] multi-module 안하고 package로 구조 나누기
- [ ] api로 cache eviction 옵션 줄 수 있게 설계하면 좋겠다 우선은 LRU
- [x] response error 방어로직
- [x] exception handler
- [ ] ~~

### 구조
- api path로 service api  / cache(+db) / 로 우선 나누기
- 각 controller에서는 참조하는 directory/package를 분리
----
### 고민
* multi server 환경에선??
*
